name: prlenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - asttokens
  - blas
  - bzip2
  - ca-certificates
  - comm
  - debugpy
  - decorator
  - exceptiongroup
  - executing
  - expat
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - jedi
  - jupyter_client
  - jupyter_core
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libsodium
  - libstdcxx-ng
  - libuuid
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nest-asyncio
  - numpy
  - numpy-base
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pip
  - platformdirs
  - ptyprocess
  - pure_eval
  - python
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tbb
  - tk
  - tornado
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - absl-py
      - appdirs
      - blender
      - certifi
      - cffi
      - charset-normalizer
      - click
      - contourpy
      - cryptography
      - cycler
      - docker-pycreds
      - docutils
      - drjit
      - filelock
      - fonttools
      - fsspec
      - gitdb
      - gitpython
      - grpcio
      - idna
      - imageio
      - imageio-ffmpeg
      - ipython
      - ipywidgets
      - jaraco-classes
      - jaraco-context
      - jaraco-functools
      - jeepney
      - jinja2
      - jupyterlab-widgets
      - keyring
      - kiwisolver
      - lazy-loader
      - lpips
      - markdown
      - markdown-it-py
      - markupsafe
      - matplot
      - matplotlib
      - matplotlib-inline
      - mdurl
      - mitsuba
      - more-itertools
      - mpmath
      - networkx
      - nh3
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - opencv-python
      - openexr
      - pillow
      - pkginfo
      - prompt-toolkit
      - protobuf
      - psutil
      - pycparser
      - pygments
      - pyloco
      - pyparsing
      - python-dateutil
      - pyyaml
      - readme-renderer
      - requests
      - requests-toolbelt
      - rfc3986
      - rich
      - scikit-image
      - scipy
      - secretstorage
      - sentry-sdk
      - setproctitle
      - simplewebsocketserver
      - smmap
      - stack-data
      - sympy
      - tensorboard
      - tensorboard-data-server
      - tifffile
      - torch
      - torchvision
      - tqdm
      - traitlets
      - twine
      - typing
      - typing-extensions
      - urllib3
      - ushlex
      - wandb
      - websocket-client
      - werkzeug
      - widgetsnbextension
      - zipp

  